language: java
addons:
  sonarcloud:
    organization: "csys-fresher-batch-2019"
    token:
      secure: "524b10033955b909d57f455161728251209533c4"

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=csys-fresher-batch-2019_wallet-karthick
